batch_size: 128
c_out: 1
checkpoints: ./my_checkpoints/PatchTST/
config_path: ./configs/multiple_datasets.yml
context_mode: 0
cos: 0
cov_mode: OT
d_ff: 128
d_model: 128
data: m5
data_name: M5
data_path: m5.csv
datasets: M5
decay_fac: 0.5
dropout: 0.1
e_layers: 2
electri_multiplier: 1
embed: timeF
enc_in: 7
equal: 1
eval_data: M5
features: MS
few_shot_ratio: 1.0
freeze: 1
freq: h
gpt_layers: 6
group_flag: 0
hid_dim: 16
is_gpt: 1
itr: 1
kernel_size: 25
label_len: 14
learning_rate: 0.0001
load_checkpoint_path: ''
loss_func: mse
lradj: type4
m5_con_category: WI_2
m5_con_state: HOUSEHOLD_2
m5_eval_mode: private
m5_root_path: ./dataset_ours/m5_wei/
max_len: -1
model: PatchTST
model_id: WI_2_HOUSEHOLD_2
n_heads: 4
no_stl_loss: false
num_nodes: 1
num_workers: 16
patch_size: 16
patience: 3
percent: 100
pool: false
pred_len: 28
pretrain: 1
prompt: 1
root_path: ./dataset_ours/m5_wei/
run_mode: PreTrain
seq_len: 366
stl_weight: 0.001
stride: 8
target: OT
target_data: M5
target_num: 1
task_name: long_term_forecast
tmax: 20
traffic_multiplier: 1
train_epochs: 10
use_token: 0
